version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: chat-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - chat-network

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    container_name: chat-backend
    ports:
      - "3100:3100"
    environment:
      - PORT=3100
      - REDIS_URL=redis://redis:6379
      - CORS_ORIGIN=*
      - SERVER_ID=backend-1
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - chat-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    container_name: chat-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SOCKET_URL=http://localhost:3000
    depends_on:
      - backend
    networks:
      - chat-network
    restart: unless-stopped

volumes:
  redis-data:

networks:
  chat-network:
    driver: bridge
